name: Deploy on Now
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy
        uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: --target production