name: Deploy on Now
on:
  push:
    branches: master
  repository_dispatch:
    types: [octokit-routes-release]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: deploy
        run: bin/deploy.sh
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
